// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFPrvTHESU_RdqWagybo7WDvY5NKFx_4',
    appId: '1:746207251726:web:420d002932349e4d79db5f',
    messagingSenderId: '746207251726',
    projectId: 'mobile-nirwana-5f8aa',
    authDomain: 'mobile-nirwana-5f8aa.firebaseapp.com',
    storageBucket: 'mobile-nirwana-5f8aa.firebasestorage.app',
    measurementId: 'G-LRLT8HERXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOmj10CXKZyHx_-kHdnCnC3MsarI07j_Q',
    appId: '1:746207251726:android:3b0d61117c41a2a579db5f',
    messagingSenderId: '746207251726',
    projectId: 'mobile-nirwana-5f8aa',
    storageBucket: 'mobile-nirwana-5f8aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLFoK4mTyvbkSArvsDiSstaApMGiCqW6g',
    appId: '1:746207251726:ios:33033c89dc82564479db5f',
    messagingSenderId: '746207251726',
    projectId: 'mobile-nirwana-5f8aa',
    storageBucket: 'mobile-nirwana-5f8aa.firebasestorage.app',
    iosBundleId: 'com.example.mobileNirwana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLFoK4mTyvbkSArvsDiSstaApMGiCqW6g',
    appId: '1:746207251726:ios:33033c89dc82564479db5f',
    messagingSenderId: '746207251726',
    projectId: 'mobile-nirwana-5f8aa',
    storageBucket: 'mobile-nirwana-5f8aa.firebasestorage.app',
    iosBundleId: 'com.example.mobileNirwana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMFPrvTHESU_RdqWagybo7WDvY5NKFx_4',
    appId: '1:746207251726:web:9883fa2133ec797d79db5f',
    messagingSenderId: '746207251726',
    projectId: 'mobile-nirwana-5f8aa',
    authDomain: 'mobile-nirwana-5f8aa.firebaseapp.com',
    storageBucket: 'mobile-nirwana-5f8aa.firebasestorage.app',
    measurementId: 'G-RN7JMSQF75',
  );
}
